/* grammar.java */
/* Generated By:JavaCC: Do not edit this line. grammar.java */
package compilador;

import java.util.Stack;
import java.util.HashMap;
import java.util.ArrayList;
import java.io.InputStream;
import java.io.FileNotFoundException;

public class grammar implements grammarConstants {
  public static boolean declaracaoMain = false;

  static class Escopo {
        String nome;
        Escopo pai;
        Map< String, SimboloInfo> simbolos = new HashMap<>();

        Escopo(String nome, Escopo pai) {
                this.nome = nome;
                this.pai = pai;
        }
  }

  static class SimboloInfo {
        String nome;
        String categoria;
        Map< String, String> propriedades;
        Escopo escopo;

        SimboloInfo(String nome, String cat,Map< String, String> prop, Escopo escopo) {
                this.nome = nome;
                this.categoria = cat;
                this.propriedades = prop != null ? prop: new HashMap< >();
                this.escopo = escopo;
                aplicarPadroes();
                verificarPropCateg(prop);
        }

        private void aplicarPadroes() {
                if (categoria.equals("var")) {
                        propriedades.putIfAbsent("mut", "nao");
                        propriedades.putIfAbsent("tipo", "inteiro");
                }
                if(categoria.equals("funcao")) {
                        propriedades.putIfAbsent("retorna", "nada");
                        propriedades.putIfAbsent("escopo", "global");
                }
        }

        private void verificarPropCarac(Map< String, String> prop) throws ParseException {
        if(prop == null || prop.isEmpty()) {
                return;
                }

        for(Map.Entry< String, String> entry: prop.entrySet()) {

            String p = entry.getKey();
            String c = entry.getValue();

                        switch(p) {
                                case "assin":
                                        if(!(c.equals("main") || c.equals("while") || c.equals("for"))) {
                                        throw new Error("A propriedade '"+ p + "' nao aceita o valor '"+ c + "'.");
                                        }
                                        if (c.equals("main")) {
                                                if(declaracaoMain) {
                                                        throw new Error("Erro semantico: A funcao com assinatura 'main' ja foi declarada.");
                                                }
                                                declaracaoMain = true;
                                        }
                                        break;
                                case "tipo" :
                                case "retorna" :
                                        if (!(c.equals("inteiro") || c.equals("frac") || c.equals("booleano") || c.equals("car") || c.equals("nada"))) {
                                                throw new Error("A propriedade '"+ p + "' nao aceita o valor '"+ c+ "'.");
                                        } break;
                                case "mut" :
                                        if (!(c.equals("sim") || c.equals("nao") || c.equals("repetivel"))) {
                                                throw new Error("A propriedade '"+ p + "' nao aceita o valor '"+ c+ "'.");
                                        } break;

                                default: break;
                        }
                }
        }

  }

  private static void verificarEscopo(String nome, Escopo escopoAtual) {
        if(escopoAtual.simbolos.containsKey(nome)) {
                throw new Error("Identificador '" + nome +"' ja declarado no escopo '"+ escopoAtual.nome +"'!");

        }
  }

  private static void declararAlgo(
    String nome,
    String cat,
    Map<String,String> prop,
    Escopo escopoAtual
  )throws ParseException {

        verificarEscopo(nome, escopoAtual);

        SimboloInfo novo = new SimboloInfo(nome, cat, prop, escopoAtual);
        escopoAtual.simbolos.put(nome, novo);
  }

  public static void main(String args []) throws ParseException, FileNotFoundException
  {
    if(args.length < 1) {
                System.err.println("Erro: Forneca o caminho do arquivo .txt");
                System.err.println("Uso: java compilador.grammar < entrada.txt >");
                System.exit(1);
    }

    try {
                java.io.FileInputStream arquivo = new java.io.FileInputStream(args[0]);
        tabelaSimbolos.push(new HashMap< String, SimboloInfo >());

        grammar parser = new grammar(arquivo);
        System.out.println("Lendo arquivo: "+ args[0]);
        parser.inicio();
        System.out.println("Ok. Arquivo processado com sucesso.");

    } catch (FileNotFoundException e) {
        System.err.println("Erro: Arquivo nao encontrado.");
    } catch (ParseException e) {
        System.err.println("Erro sintatico: "+ e.getMessage());
    } catch (Error e ) {
                System.err.println("Erro semantico: "+ e.getMessage());
    }
  }

  static final public int inicio() throws ParseException, ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABREBLOCO:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      declaracao();
    }
{if ("" != null) return 0;}
    throw new Error("Missing return statement in function");
}

  static final public Token verdadeiroOuFalso() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VERDADEIRO:{
      jj_consume_token(VERDADEIRO);
{if ("" != null) return token;}
      break;
      }
    case FALSO:{
      jj_consume_token(FALSO);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:{
      jj_consume_token(TIPO_INT);
{if ("" != null) return token;}
      break;
      }
    case TIPO_CHAR:{
      jj_consume_token(TIPO_CHAR);
{if ("" != null) return token;}
      break;
      }
    case TIPO_FLOAT:{
      jj_consume_token(TIPO_FLOAT);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token escopo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIS_GLOBAL:{
      jj_consume_token(VIS_GLOBAL);
{if ("" != null) return token;}
      break;
      }
    case VIS_LOOPS:{
      jj_consume_token(VIS_LOOPS);
{if ("" != null) return token;}
      break;
      }
    case ID:{
      jj_consume_token(ID);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token tipo_declaracao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DECLARAVAR:{
      jj_consume_token(DECLARAVAR);
{if ("" != null) return token;}
      break;
      }
    case DECLARAFUNC:{
      jj_consume_token(DECLARAFUNC);
{if ("" != null) return token;}
      break;
      }
    case DECLARA_DECLARA:{
      jj_consume_token(DECLARA_DECLARA);
{if ("" != null) return token;}
      break;
      }
    case LOOP_WHILE:{
      jj_consume_token(LOOP_WHILE);
{if ("" != null) return token;}
      break;
      }
    case LOOP_FOR:{
      jj_consume_token(LOOP_FOR);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token declaracao() throws ParseException, ParseException {Token id = null;
        String nomeEscopo = new String();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      id = jj_consume_token(ID);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(ABREBLOCO);
if( id != null)
     {
       nomeEscopo = "global";

     }else {
       nomeEscopo = id.image;
     }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABREPARENT:
      case DECLARAVAR:
      case DECLARAFUNC:
      case DECLARA_DECLARA:
      case LOOP_WHILE:
      case LOOP_FOR:
      case ID:
      case INTEIRO:
      case REAL:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DECLARAVAR:
      case DECLARAFUNC:
      case DECLARA_DECLARA:
      case LOOP_WHILE:
      case LOOP_FOR:{
        declara();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        if (jj_2_1(2)) {
          chamada();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ABREPARENT:
          case ID:
          case INTEIRO:
          case REAL:{
            expressao();
            break;
            }
          default:
            jj_la1[8] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
    jj_consume_token(FECHABLOCO);
{if ("" != null) return nomeBloco;}
    throw new Error("Missing return statement in function");
}

  static final public void declara() throws ParseException {Token nomeVar = null, prop = null, car = null;
        String tipoVar = "indefinido";
        boolean declarado = false;
    tipo_declaracao();
    jj_consume_token(DECLARADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      nomeVar = jj_consume_token(ID);
      break;
      }
    case ABREPARENT:{
      booleano();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      atribuicao();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEPARADOR:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_3;
      }
      jj_consume_token(SEPARADOR);
      prop = propriedades();
      jj_consume_token(DECLARADOR);
      car = caracteristica();
verificarPropCarac(prop, car);
    }
    jj_consume_token(FIM);
if (nomeVar != null) {
      declararVariavel(nomeVar.image, tipoVar);
      }
}

  static final public void atribuicao() throws ParseException {
    jj_consume_token(ATRIBUICAO);
    expressao();
}

  static final public Token propriedades() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PROP_TIPO:{
      jj_consume_token(PROP_TIPO);
{if ("" != null) return token;}
      break;
      }
    case PROP_MUTAVEL:{
      jj_consume_token(PROP_MUTAVEL);
{if ("" != null) return token;}
      break;
      }
    case PROP_RETORNA:{
      jj_consume_token(PROP_RETORNA);
{if ("" != null) return token;}
      break;
      }
    case PROP_ASSINATURA:{
      jj_consume_token(PROP_ASSINATURA);
{if ("" != null) return token;}
      break;
      }
    case PROP_ESCOPO:{
      jj_consume_token(PROP_ESCOPO);
{if ("" != null) return token;}
      break;
      }
    case PROP_PARAMETROS:{
      jj_consume_token(PROP_PARAMETROS);
{if ("" != null) return token;}
      break;
      }
    case PROP_CONDICAO:{
      jj_consume_token(PROP_CONDICAO);
{if ("" != null) return token;}
      break;
      }
    case PROP_ENTAO:{
      jj_consume_token(PROP_ENTAO);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token caracteristica() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_CHAR:
    case TIPO_FLOAT:{
      t = tipo();
{if ("" != null) return t;}
      break;
      }
    case VERDADEIRO:
    case FALSO:{
      t = verdadeiroOuFalso();
{if ("" != null) return t;}
      break;
      }
    case VAR_REPETIVEL:{
      t = jj_consume_token(VAR_REPETIVEL);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_2(2147483647)) {
        escopo();
{if ("" != null) return t;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ABREBLOCO:
        case ID:{
          t = declaracao();
{if ("" != null) return t;}
          break;
          }
        case ASSIN_MAIN:
        case ASSIN_WHILE:
        case ASSIN_FOR:{
          t = assinatura();
{if ("" != null) return t;}
          break;
          }
        case ABREPARENT:{
          t = booleano();
{if ("" != null) return t;}
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Token assinatura() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIN_MAIN:{
      jj_consume_token(ASSIN_MAIN);
{if ("" != null) return token;}
      break;
      }
    case ASSIN_WHILE:{
      jj_consume_token(ASSIN_WHILE);
{if ("" != null) return token;}
      break;
      }
    case ASSIN_FOR:{
      jj_consume_token(ASSIN_FOR);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token booleano() throws ParseException {Token t;
    t = jj_consume_token(ABREPARENT);
    expressao();
    operador_bool();
    expressao();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:
      case OR:
      case MAIOR:
      case MENOR:
      case MAIOR_IGUAL:
      case MENOR_IGUAL:
      case IGUAL:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_4;
      }
      operador_bool();
      expressao();
    }
    jj_consume_token(FECHAPARENT);
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
}

  static final public Token operador_bool() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:{
      jj_consume_token(IGUAL);
{if ("" != null) return token;}
      break;
      }
    case MAIOR:{
      jj_consume_token(MAIOR);
{if ("" != null) return token;}
      break;
      }
    case MAIOR_IGUAL:{
      jj_consume_token(MAIOR_IGUAL);
{if ("" != null) return token;}
      break;
      }
    case MENOR:{
      jj_consume_token(MENOR);
{if ("" != null) return token;}
      break;
      }
    case MENOR_IGUAL:{
      jj_consume_token(MENOR_IGUAL);
{if ("" != null) return token;}
      break;
      }
    case OR:{
      jj_consume_token(OR);
{if ("" != null) return token;}
      break;
      }
    case AND:{
      jj_consume_token(AND);
{if ("" != null) return token;}
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public void expressao() throws ParseException {
    multiplicacao();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIS:
      case MENOS:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIS:{
        jj_consume_token(MAIS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      multiplicacao();
    }
}

  static final public void multiplicacao() throws ParseException {
    fator();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICA:
      case DIVIDE:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICA:{
        jj_consume_token(MULTIPLICA);
        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
    }
}

  static final public void fator() throws ParseException, ParseException {Token id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      id = jj_consume_token(ID);
try {
                                verificarVariavel(id.image);
                        } catch (ParseException e) {
                                                {if (true) throw new Error(e.getMessage());}
                          }
      break;
      }
    case REAL:{
      jj_consume_token(REAL);
      break;
      }
    case INTEIRO:{
      jj_consume_token(INTEIRO);
      break;
      }
    case ABREPARENT:{
      jj_consume_token(ABREPARENT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABREPARENT:
      case ID:
      case INTEIRO:
      case REAL:{
        expressao();
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        fator();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(FECHAPARENT);
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void chamada() throws ParseException, ParseException {Token id;
    id = jj_consume_token(ID);
verificarVariavel(id.image);
    atribuicao();
    jj_consume_token(FIM);
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_3R_atribuicao_304_3_8()
 {
    if (jj_scan_token(ATRIBUICAO)) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_chamada_393_3_7()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    return false;
  }

  static private boolean jj_3R_chamada_393_3_7()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_3R_atribuicao_304_3_8()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public grammarTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x100000,0x0,0x0,0x0,0x7000000,0x0,0x7400000,0x7000000,0x400000,0x400000,0x20000,0x80000,0xf0000000,0x0,0x500000,0x0,0xfe00,0xfe00,0x60,0x60,0x180,0x180,0x400040,0x400000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x100000,0x600,0x70,0x102800,0xc0000,0x100000,0x7c0000,0xc0000,0x700000,0x100000,0x0,0x0,0xf,0x20670,0x11c000,0x1c000,0x0,0x0,0x0,0x0,0x0,0x0,0x700000,0x700000,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public grammar(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public grammar(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new grammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public grammar(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new grammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new grammarTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public grammar(grammarTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(grammarTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[55];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 24; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 55; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
