/* Generated By:JavaCC: Do not edit this line. grammarConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int MULTIPLICA = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int MAIOR = 11;
  /** RegularExpression Id. */
  int MENOR = 12;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 13;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 14;
  /** RegularExpression Id. */
  int IGUAL = 15;
  /** RegularExpression Id. */
  int DECLARADOR = 16;
  /** RegularExpression Id. */
  int ATRIBUICAO = 17;
  /** RegularExpression Id. */
  int FIM = 18;
  /** RegularExpression Id. */
  int SEPARADOR = 19;
  /** RegularExpression Id. */
  int ABREBLOCO = 20;
  /** RegularExpression Id. */
  int FECHABLOCO = 21;
  /** RegularExpression Id. */
  int ABREPARENT = 22;
  /** RegularExpression Id. */
  int FECHAPARENT = 23;
  /** RegularExpression Id. */
  int DECLARAVAR = 24;
  /** RegularExpression Id. */
  int DECLARAFUNC = 25;
  /** RegularExpression Id. */
  int DECLARA_DECLARA = 26;
  /** RegularExpression Id. */
  int DECLARAESTRUT = 27;
  /** RegularExpression Id. */
  int PROP_TIPO = 28;
  /** RegularExpression Id. */
  int PROP_MUTAVEL = 29;
  /** RegularExpression Id. */
  int PROP_ESCOPO = 30;
  /** RegularExpression Id. */
  int PROP_ASSINATURA = 31;
  /** RegularExpression Id. */
  int PROP_PARAMETROS = 32;
  /** RegularExpression Id. */
  int PROP_RETORNA = 33;
  /** RegularExpression Id. */
  int PROP_CONDICAO = 34;
  /** RegularExpression Id. */
  int PROP_ENTAO = 35;
  /** RegularExpression Id. */
  int TIPO_INT = 36;
  /** RegularExpression Id. */
  int TIPO_CHAR = 37;
  /** RegularExpression Id. */
  int TIPO_FLOAT = 38;
  /** RegularExpression Id. */
  int TIPO_BOOL = 39;
  /** RegularExpression Id. */
  int TIPO_VOID = 40;
  /** RegularExpression Id. */
  int VERDADEIRO = 41;
  /** RegularExpression Id. */
  int FALSO = 42;
  /** RegularExpression Id. */
  int VIS_GLOBAL = 43;
  /** RegularExpression Id. */
  int VIS_FUNCOES = 44;
  /** RegularExpression Id. */
  int VIS_LOOPS = 45;
  /** RegularExpression Id. */
  int ASSIN_MAIN = 46;
  /** RegularExpression Id. */
  int ASSIN_WHILE = 47;
  /** RegularExpression Id. */
  int ASSIN_FOR = 48;
  /** RegularExpression Id. */
  int VAR_REPETIVEL = 49;
  /** RegularExpression Id. */
  int LOOP_WHILE = 50;
  /** RegularExpression Id. */
  int LOOP_FOR = 51;
  /** RegularExpression Id. */
  int ID = 52;
  /** RegularExpression Id. */
  int INTEIRO = 53;
  /** RegularExpression Id. */
  int REAL = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\":\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"var\"",
    "\"funcao\"",
    "\"declaracao\"",
    "\"estrutura\"",
    "\"tipo\"",
    "\"mut\"",
    "\"escopo\"",
    "\"assin\"",
    "\"param\"",
    "\"retorna\"",
    "\"condicao\"",
    "\"entao\"",
    "\"inteiro\"",
    "\"car\"",
    "\"frac\"",
    "\"booleano\"",
    "\"nada\"",
    "\"sim\"",
    "\"nao\"",
    "\"global\"",
    "\"funcoes\"",
    "\"loops\"",
    "\"main\"",
    "\"while\"",
    "\"for\"",
    "\"repetivel\"",
    "\"enquanto\"",
    "\"para\"",
    "<ID>",
    "<INTEIRO>",
    "<REAL>",
  };

}
